services:
  - type: web
    name: big-daddy-v3-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run web
    envVars:
      - key: WEB_DOMAIN
        value: https://host-bigdaddyv3teleweb.onrender.com

  - type: web
    name: big-daddy-v3-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
